backend:
  name: github
  repo: chaddugas/me
  branch: master
  accept_roles:
    - admin
    - editor

site_url: https://www.chaddugas.me
display_url: https://www.chaddugas.me
# logo_url: https://your-site.com/images/logo.svg

show_preview_links: true

media_folder: "static/media"
public_folder: "/media"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "main-navigation"
    label: "Main Navigation"
    folder: "static/data/main-nav"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - label: "Sub Navigation"
        name: "subs"
        widget: "list"
        required: false
        allow_add: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Icon Class", name: "icon", widget: "string"}
  - name: "main-banner"
    label: "Main Banner"
    folder: "static/data/main-banner"
    fields:
      - {label: "Super Text", name: "super", widget: "string"}
      - {label: "Main Text", name: "main", widget: "string"}
      - {label: "Sub Text", name: "sub", widget: "string"}
      - label: "Featured Image"
        name: "image"
        widget: "image"
        allow_multiple: false
