backend:
  name: github
  repo: chaddugas/me
  branch: master
  accept_roles:
    - admin
    - editor

site_url: https://www.chaddugas.me
display_url: https://www.chaddugas.me

show_preview_links: true

media_folder: "static/media"
public_folder: "/media"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "main-navigation"
    label: "Main Navigation"
    folder: "main-nav"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - label: "Sub Navigation"
        name: "subs"
        widget: "list"
        required: false
        allow_add: true
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Icon Class", "icon", widget: "string"}
