backend:
  name: git-gateway
  branch: master
  accept_roles:
    - admin
    - editor

site_url: https://chaddugas.me
display_url: https://chaddugas.me
logo_url: /media/logo/logo.png

show_preview_links: true

media_folder: 'static/media'
public_folder: '/media'

collections:
  - name: 'content'
    label: 'Site Content'
    editor:
      preview: false
    files:
      - name: 'projects'
        label: 'Projects' 
        file: 'static/data/projects.json'
        fields:
          - label: 'Projects' 
            name: 'projects'
            widget: 'list'
            allow_add: true
            required: true
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Photo', name: 'photo', widget: 'image'}
              - {label: 'Secondary Photo', name: 'secondary_photo', widget: 'image', required: false}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - {label: 'Visible', name: 'visible', widget: 'boolean', default: true}

      - name: 'contact'
        label: 'Contacts' 
        file: 'static/data/contact.json'
        fields:
          - {label: 'Title', name: 'title', widget: 'markdown'}
          - label: 'Contact Item' 
            name: 'contacts'
            widget: 'list'
            allow_add: true
            required: true
            fields:
              - {label: 'Logo', name: 'logo', widget: 'string'}
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Information', name: 'info', widget: 'text'}
              - {label: 'Link', name: 'link', widget: 'string'}